# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='klopvalues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klopid', models.CharField(max_length=10)),
                ('heart_rate', models.IntegerField(default=0)),
                ('resp_rate', models.IntegerField(default=0)),
                ('blood_pressure_sys', models.IntegerField(default=0)),
                ('blood_pressure_dia', models.IntegerField(default=0)),
                ('sugar_level', models.IntegerField(default=0)),
                ('spo2_content', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initid', models.CharField(max_length=10)),
                ('relatedid', models.CharField(max_length=10)),
            ],
        ),
    ]
