# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medwebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='watchervalues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watcherid', models.CharField(max_length=10)),
                ('heart_rate', models.IntegerField(default=0)),
                ('resp_rate', models.IntegerField(default=0)),
                ('blood_pressure_sys', models.IntegerField(default=0)),
                ('blood_pressure_dia', models.IntegerField(default=0)),
                ('sugar_level', models.IntegerField(default=0)),
                ('spo2_content', models.IntegerField(default=0)),
                ('ECG_pattern', models.CharField(max_length=4000)),
            ],
        ),
        migrations.DeleteModel(
            name='klopvalues',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='klopid',
            new_name='watcherid',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='klopid',
            new_name='watcherid',
        ),
    ]
