# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medwebapp', '0003_userprofile_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='watcheradvicelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watcherid', models.CharField(max_length=10)),
                ('watcheradvice', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='profiles',
        ),
    ]
