# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medwebapp', '0004_auto_20160313_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='watcherwave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watcherid', models.CharField(max_length=10)),
                ('ppg_pattern', models.CharField(blank=True, max_length=4000)),
                ('ECG_pattern', models.CharField(blank=True, max_length=4000)),
            ],
        ),
        migrations.AlterField(
            model_name='watcheradvicelist',
            name='watcheradvice',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='watchervalues',
            name='ECG_pattern',
            field=models.CharField(blank=True, max_length=4000),
        ),
    ]
