# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medwebapp', '0006_auto_20160316_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchervalues',
            name='ECG_pattern',
        ),
    ]
