# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medwebapp', '0007_remove_watchervalues_ecg_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchervalues',
            name='haemoglobin',
            field=models.IntegerField(default=0),
        ),
    ]
