# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medwebapp', '0008_watchervalues_haemoglobin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchervalues',
            name='haemoglobin',
        ),
        migrations.AddField(
            model_name='watchervalues',
            name='ECG_pattern',
            field=models.CharField(blank=True, max_length=40000),
        ),
    ]
