# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medwebapp', '0009_auto_20160317_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchervalues',
            name='ECG_pattern',
        ),
        migrations.AddField(
            model_name='watchervalues',
            name='haemoglobin',
            field=models.IntegerField(default=0),
        ),
    ]
