# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medwebapp', '0010_auto_20160317_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='watcherdetails',
            fields=[
                ('watcherid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('heart_rate', models.IntegerField(default=0)),
                ('resp_rate', models.IntegerField(default=0)),
                ('blood_pressure_sys', models.IntegerField(default=0)),
                ('blood_pressure_dia', models.IntegerField(default=0)),
                ('sugar_level', models.IntegerField(default=0)),
                ('spo2_content', models.IntegerField(default=0)),
                ('hb', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='watchervalues',
        ),
    ]
